services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: petradar-db
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data_db:/var/lib/postgresql/data

volumes:
  postgres_data_db: