services:
  pet-radar-api:
    build:
      context: ./pet-radar-api
    image: pet-radar-api:latest
    container_name: PetRadarAPI
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      PORT: ${PORT}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CACHE_TTL_MS: ${CACHE_TTL_MS}
      APPINSIGHTS_CONNECTION_STRING: ${APPINSIGHTS_CONNECTION_STRING}
      
  postgres:
    image: postgis/postgis:16-master
    container_name: PostgresDB
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
 
  redis:
    image: redis
    container_name: PetRadarRedis
    ports:
      - 6379:6379
    volumes:
      - redis_data_db:/data
 
volumes:
  postgres_data_db:
  redis_data_db: